/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description Profile, global role and outlet memberships for the current session.
         *
         *     The client uses this to decide which shell to render, so it is the first
         *     call after sign-in.
         */
        get: operations["read_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update your own details
         * @description Change your own name or phone. Role, outlets and activation are not
         *     editable here — those are administrative actions.
         */
        patch: operations["update_me_users_me_patch"];
        trace?: never;
    };
    "/users/roles/grantable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Roles you may assign
         * @description What the signed-in user may grant, plus a plain-language reason for each
         *     role they may not. The UI disables the rest with the reason attached rather
         *     than omitting them — a rule you cannot see is a rule you will argue with.
         */
        get: operations["get_grantable_roles_users_roles_grantable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * People you can administer
         * @description Owners and operations managers see everyone. An outlet manager sees only
         *     people in their own outlets.
         */
        get: operations["list_users_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite someone
         * @description Supabase sends the invitation and owns the token, so no password is ever
         *     handled here.
         *
         *     You can never grant a role at or above your own. An existing address is not
         *     an error: that person keeps the login they already have.
         */
        post: operations["invite_user_users_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One person */
        get: operations["get_user_users__profile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update someone's details
         * @description Deactivating the last active owner is refused: it would lock everyone out
         *     of outlet and user administration permanently.
         */
        patch: operations["update_user_users__profile_id__patch"];
        trace?: never;
    };
    "/users/{profile_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change someone's role
         * @description Outlet roles follow the global role, so the two cannot silently disagree.
         */
        put: operations["set_user_role_users__profile_id__role_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{profile_id}/outlets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace someone's outlets
         * @description Replaces the whole set. The first outlet becomes their primary.
         */
        put: operations["set_user_outlets_users__profile_id__outlets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{profile_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set or clear a shared-tablet PIN
         * @description A PIN attributes floor work on a shared tablet to a real person. It
         *     authorises floor actions only, can never approve a run, and is only accepted
         *     on a device already bound to that person's outlet.
         *
         *     Sending `null` clears it, which is how a departing staff member comes off
         *     the tablet without losing their history. Only shift leads and staff may
         *     have one.
         */
        put: operations["set_user_pin_users__profile_id__pin_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outlets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Outlets you can see
         * @description Owners and operations managers see every outlet. Everyone else sees only
         *     the outlets they belong to.
         */
        get: operations["list_outlets_outlets_get"];
        put?: never;
        /**
         * Create an outlet
         * @description Owner only. The code must be unique and is fixed once created.
         */
        post: operations["create_outlet_outlets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outlets/{outlet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One outlet */
        get: operations["get_outlet_outlets__outlet_id__get"];
        put?: never;
        post?: never;
        /**
         * Close an outlet
         * @description Owner only. A soft delete: history is kept, the outlet stops appearing.
         *
         *     Refused with 409 while any checklist run is still pending, in progress or
         *     awaiting review — closing the outlet under them would strand work someone
         *     is in the middle of.
         */
        delete: operations["delete_outlet_outlets__outlet_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update an outlet
         * @description Owner only. Changes only the fields present in the body. The code cannot
         *     be changed — it appears in exports and printed sheets.
         */
        patch: operations["update_outlet_outlets__outlet_id__patch"];
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registered tablets */
        get: operations["list_devices_devices_get"];
        put?: never;
        /**
         * Register a tablet
         * @description Owner only. Binds an existing Supabase auth account to one outlet.
         *
         *     The account itself is created out of band, so this API never mints or
         *     transports a credential.
         */
        post: operations["register_device_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a tablet
         * @description Owner only. Use this the moment a tablet goes missing: it stops that
         *     account reaching any outlet data, without touching the runs it already
         *     recorded.
         */
        delete: operations["revoke_device_devices__device_id__delete"];
        options?: never;
        head?: never;
        /** Rename or suspend a tablet */
        patch: operations["update_device_devices__device_id__patch"];
        trace?: never;
    };
    "/inventory/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Departments (count stations) */
        get: operations["list_departments_inventory_departments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item categories */
        get: operations["list_categories_inventory_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The item catalogue
         * @description The shared catalogue. Levels are included for the outlets the caller can
         *     see, so an outlet manager reads their own pars without seeing another
         *     outlet's.
         */
        get: operations["list_items_inventory_items_get"];
        put?: never;
        /**
         * Add an item to the catalogue
         * @description Owner or operations manager. The item becomes available to every outlet;
         *     each outlet sets its own par level.
         */
        post: operations["create_item_inventory_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Retire a catalogue item
         * @description Soft delete. History and past counts keep pointing at it; it simply
         *     stops appearing in the catalogue and on count sheets.
         */
        delete: operations["delete_item_inventory_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Edit a catalogue item */
        patch: operations["update_item_inventory_items__item_id__patch"];
        trace?: never;
    };
    "/inventory/items/{item_id}/levels/{outlet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set an outlet's par level for an item
         * @description An outlet manager sets levels for their own outlet; owners and
         *     operations managers for any. is_stocked false means the outlet deliberately
         *     does not carry the item, which is different from never having configured it.
         */
        put: operations["set_level_inventory_items__item_id__levels__outlet_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every setting with its current value
         * @description The full registry, each key resolved to the value in force right now at
         *     global scope. Grouped client-side by `group`.
         */
        get: operations["list_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{key}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every value this setting has held */
        get: operations["setting_history_settings__key__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change a setting
         * @description Inserts a new effective-dated row rather than editing the old one, so
         *     scoring a past period keeps using the values that were live then.
         *
         *     Scoring weights and bands are owner-only; the operational groups
         *     (integrity, AI review, jobs) accept an operations manager too.
         */
        put: operations["set_setting_settings__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent job executions
         * @description Newest first. A gap where a scheduled job should have run is as
         *     significant as a failure row — both mean the job did not do its work.
         */
        get: operations["list_job_runs_jobs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe. Must never touch the database.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe. Unlike /healthz this does check the database, because a
         *     process that cannot reach Postgres is running but not serving.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Category */
        Category: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Label Bn */
            label_bn: string | null;
            /** Sort Order */
            sort_order: number;
        };
        /** CreateItemRequest */
        CreateItemRequest: {
            /** Name */
            name: string;
            /** Name Bn */
            name_bn?: string | null;
            /**
             * Department Id
             * Format: uuid
             */
            department_id: string;
            /** Category Id */
            category_id?: string | null;
            unit: components["schemas"]["InventoryUnit"];
            /** Notes */
            notes?: string | null;
        };
        /** CreateOutletRequest */
        CreateOutletRequest: {
            /** Name */
            name: string;
            /** Address Line */
            address_line?: string | null;
            /** City */
            city?: string | null;
            /** Geo Lat */
            geo_lat?: number | null;
            /** Geo Lng */
            geo_lng?: number | null;
            /**
             * Geofence Radius M
             * @default 150
             */
            geofence_radius_m: number;
            /**
             * Timezone
             * @default Asia/Kolkata
             */
            timezone: string;
            /** Opened On */
            opened_on?: string | null;
            /** Code */
            code: string;
        };
        /** Department */
        Department: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Label Bn */
            label_bn: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
        };
        /** Device */
        Device: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Outlet Id
             * Format: uuid
             */
            outlet_id: string;
            /** Outlet Code */
            outlet_code: string;
            /** Outlet Name */
            outlet_name: string;
            /** Label */
            label: string;
            /** Is Active */
            is_active: boolean;
            /** Last Seen At */
            last_seen_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DeviceSummary
         * @description Present only when the caller is a shared outlet tablet.
         */
        DeviceSummary: {
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /**
             * Outlet Id
             * Format: uuid
             */
            outlet_id: string;
            /** Label */
            label: string;
        };
        /**
         * GrantableRolesResponse
         * @description What the signed-in user may assign, so the UI can disable the rest with
         *     an explanation instead of hiding it.
         */
        GrantableRolesResponse: {
            /** Grantable */
            grantable: components["schemas"]["UserRole"][];
            /** All Roles */
            all_roles: components["schemas"]["UserRole"][];
            /** Reasons */
            reasons: {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InventoryUnit
         * @enum {string}
         */
        InventoryUnit: "piece" | "gram" | "kilogram" | "millilitre" | "litre" | "roll" | "packet" | "box" | "bottle" | "jug";
        /** InviteUserRequest */
        InviteUserRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            global_role: components["schemas"]["UserRole"];
            /** Outlet Ids */
            outlet_ids: string[];
            /** Employee Code */
            employee_code?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** InviteUserResponse */
        InviteUserResponse: {
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Invite Sent */
            invite_sent: boolean;
            /** Detail */
            detail: string;
        };
        /** Item */
        Item: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Name Bn */
            name_bn: string | null;
            /**
             * Department Id
             * Format: uuid
             */
            department_id: string;
            /** Department Label */
            department_label: string;
            /** Category Id */
            category_id: string | null;
            /** Category Label */
            category_label: string | null;
            unit: components["schemas"]["InventoryUnit"];
            /** Notes */
            notes: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Levels
             * @default []
             */
            levels: components["schemas"]["OutletLevel"][];
        };
        /** JobRun */
        JobRun: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Name */
            job_name: string;
            /** Status */
            status: string;
            /** Outlet Id */
            outlet_id: string | null;
            /** Business Date */
            business_date: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Error Detail */
            error_detail: string | null;
            /** Triggered By Name */
            triggered_by_name: string | null;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Employee Code */
            employee_code: string | null;
            global_role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Is Management */
            is_management: boolean;
            /** Is Global */
            is_global: boolean;
            /** Has Pin */
            has_pin: boolean;
            /** Outlets */
            outlets: components["schemas"]["OutletSummary"][];
            device?: components["schemas"]["DeviceSummary"] | null;
        };
        /** OutletLevel */
        OutletLevel: {
            /**
             * Outlet Id
             * Format: uuid
             */
            outlet_id: string;
            /** Outlet Code */
            outlet_code: string;
            /** Par Level */
            par_level: number | null;
            /** Reorder Qty */
            reorder_qty: number | null;
            /** Order Unit */
            order_unit: number | null;
            /** Is Stocked */
            is_stocked: boolean;
        };
        /** OutletResponse */
        OutletResponse: {
            /** Name */
            name: string;
            /** Address Line */
            address_line?: string | null;
            /** City */
            city?: string | null;
            /** Geo Lat */
            geo_lat?: number | null;
            /** Geo Lng */
            geo_lng?: number | null;
            /**
             * Geofence Radius M
             * @default 150
             */
            geofence_radius_m: number;
            /**
             * Timezone
             * @default Asia/Kolkata
             */
            timezone: string;
            /** Opened On */
            opened_on?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /**
             * Device Count
             * @default 0
             */
            device_count: number;
        };
        /** OutletSummary */
        OutletSummary: {
            /**
             * Outlet Id
             * Format: uuid
             */
            outlet_id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            role_at_outlet: components["schemas"]["UserRole"];
            /** Is Primary */
            is_primary: boolean;
        };
        /** RegisterDeviceRequest */
        RegisterDeviceRequest: {
            /**
             * Outlet Id
             * Format: uuid
             */
            outlet_id: string;
            /** Label */
            label: string;
            /**
             * Auth User Id
             * Format: uuid
             */
            auth_user_id: string;
        };
        /** SetLevelRequest */
        SetLevelRequest: {
            /** Par Level */
            par_level?: number | null;
            /** Reorder Qty */
            reorder_qty?: number | null;
            /** Order Unit */
            order_unit?: number | null;
            /**
             * Is Stocked
             * @default true
             */
            is_stocked: boolean;
        };
        /**
         * SetOutletsRequest
         * @description Replaces the whole membership set, rather than adding to it.
         *
         *     A replace makes the resulting state obvious from the request. An add/remove
         *     pair leaves the caller guessing what the person ended up with.
         */
        SetOutletsRequest: {
            /** Outlet Ids */
            outlet_ids: string[];
        };
        /** SetPinRequest */
        SetPinRequest: {
            /** Pin */
            pin?: string | null;
        };
        /** SetRoleRequest */
        SetRoleRequest: {
            global_role: components["schemas"]["UserRole"];
        };
        /** SetSettingRequest */
        SetSettingRequest: {
            /** Value */
            value: unknown;
            /** Note */
            note?: string | null;
            /** Effective From */
            effective_from?: string | null;
            /** Outlet Id */
            outlet_id?: string | null;
        };
        /** SettingHistoryRow */
        SettingHistoryRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scope */
            scope: string;
            /** Outlet Id */
            outlet_id: string | null;
            /** Value */
            value: unknown;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Note */
            note: string | null;
            /** Set By Name */
            set_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SettingView
         * @description One setting as the admin screen shows it: definition plus current value.
         */
        SettingView: {
            /** Key */
            key: string;
            /** Group */
            group: string;
            /** Type */
            type: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Outlet Overridable */
            outlet_overridable: boolean;
            /** Minimum */
            minimum: number | null;
            /** Maximum */
            maximum: number | null;
            /** Choices */
            choices: string[];
            /** Default */
            default: unknown;
            /** Value */
            value: unknown;
            /** Is Set */
            is_set: boolean;
        };
        /** UpdateDeviceRequest */
        UpdateDeviceRequest: {
            /** Label */
            label?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UpdateItemRequest */
        UpdateItemRequest: {
            /** Name */
            name?: string | null;
            /** Name Bn */
            name_bn?: string | null;
            /** Category Id */
            category_id?: string | null;
            unit?: components["schemas"]["InventoryUnit"] | null;
            /** Notes */
            notes?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * UpdateMeRequest
         * @description Only what a person may change about themselves.
         *
         *     Role, outlets and activation are deliberately absent: allowing them here
         *     would let anyone promote themselves through their own profile.
         */
        UpdateMeRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /**
         * UpdateOutletRequest
         * @description Every field optional: a PATCH changes only what it names.
         *
         *     `code` is absent on purpose. It appears in exports, conversation and
         *     printed sheets, so renaming it silently would break references nobody is
         *     tracking.
         */
        UpdateOutletRequest: {
            /** Name */
            name?: string | null;
            /** Address Line */
            address_line?: string | null;
            /** City */
            city?: string | null;
            /** Geo Lat */
            geo_lat?: number | null;
            /** Geo Lng */
            geo_lng?: number | null;
            /** Geofence Radius M */
            geofence_radius_m?: number | null;
            /** Timezone */
            timezone?: string | null;
            /** Opened On */
            opened_on?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UpdateUserRequest */
        UpdateUserRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Employee Code */
            employee_code?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * UserListItem
         * @description A person as they appear in the admin table.
         */
        UserListItem: {
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Employee Code */
            employee_code: string | null;
            global_role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Has Pin */
            has_pin: boolean;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Outlets */
            outlets: components["schemas"]["OutletSummary"][];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "owner" | "ops_manager" | "outlet_manager" | "shift_lead" | "staff";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_grantable_roles_users_roles_grantable_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantableRolesResponse"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: {
                outlet_id?: string | null;
                role?: components["schemas"]["UserRole"] | null;
                is_active?: boolean | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_user_users_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_users__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__profile_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_role_users__profile_id__role_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_outlets_users__profile_id__outlets_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetOutletsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_pin_users__profile_id__pin_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outlets_outlets_get: {
        parameters: {
            query?: {
                /** @description Include outlets that have been deactivated. */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutletResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_outlet_outlets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOutletRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutletResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outlet_outlets__outlet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outlet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutletResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_outlet_outlets__outlet_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outlet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_outlet_outlets__outlet_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outlet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOutletRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutletResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_devices_get: {
        parameters: {
            query?: {
                outlet_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_device_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_device_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_departments_inventory_departments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"][];
                };
            };
        };
    };
    list_categories_inventory_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    list_items_inventory_items_get: {
        parameters: {
            query?: {
                department_id?: string | null;
                search?: string | null;
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_inventory_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_inventory_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_inventory_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_level_inventory_items__item_id__levels__outlet_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
                outlet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLevelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingView"][];
                };
            };
        };
    };
    setting_history_settings__key__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingHistoryRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_setting_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSettingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_runs_jobs_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                job_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
